#!/usr/bin/env python

import os
import glob

EXCLUDED_FILES = ['.git']
def exclusion(file_name):
    for ex in EXCLUDED_FILES:
        if file_name == ex:
            return True
    return False

if __name__ == '__main__':
    # install all
    for f in glob.glob('.*'):
        if exclusion(f):
            continue
        if os.path.exists(f):
            print('File exists %s' % f)
            continue
        print('Installing ' + f)
        os.system('cd ~; ln -s .dotfiles/%s %s' % (f, f))
