#!/bin/sh

echo '===> Syncing ko-dot'
cd ~ && \
    git stash && \
    git checkout master && \
    git pull origin master && \
    git push origin master && \
    git stash pop
git submodule update --init --recursive
tmux source-file ~/.tmux.conf
tmux refresh-client -S

echo '===> Syncing ko-vim'
cd ~/.vim/ && \
    git stash && \
    git checkout develop && \
    git pull origin develop && \
    git push origin develop && \
    git stash pop
vim -u bundles.vim +BundleInstall +BundleClean! +qall
