#!/usr/bin/env sh

yabai -m config layout float
yabai -m config --space 1 layout bsp
yabai -m config split_type auto
yabai -m config window_placement second_child

yabai -m config top_padding 6
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12
# yabai -m config external_bar all:36:0

yabai -m config auto_balance off
yabai -m config split_ratio 0.50

yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off

if [ -f /tmp/kxh-daily_color.sh ]; then
    source /tmp/kxh-daily-color.sh
    COLOR="0xe0${DAILY_COLOR:2}"
else
    COLOR="0xe02d74da"
fi
yabai -m config insert_feedback_color $COLOR

yabai -m config mouse_modifier ctrl
yabai -m config mouse_drop_action stack
# yabai -m config mouse_action1 move
# yabai -m config mouse_action2 resize

# exclude apps from tiling
ignored_apps=(
    "Activity Monitor"
    "Adobe Photoshop 2024"
    "Archive Utility"
    "Autodesk Fusion"
    "BambuStudio"
    "BetterZip"
    "ChatGPT"
    "Clash Verge"
    "Cyberduck"
    "Dictionary"
    "Home"
    "IINA"
    "Installer"
    "Logi Options"
    "Logitech Options"
    "LuLu"
    "Microsoft PowerPoint"
    "Microsoft Word"
    "Nebula for Mac"
    "NetEaseMusic"
    "Netiquette"
    "OrcaSlicer"
    "PICO-8"
    "Parallels"
    "Photo Booth"
    "Photos"
    "Preview"
    "QuickTime Player"
    "Reminders"
    "Safari"
    "Stickies"
    "Stocks"
    "System Information"
    "System Settings"
    "Telegram"
    "VLC"
    "iPhone Mirroring"
)
for app in "${ignored_apps[@]}"; do
    yabai -m rule --add app="${app}" manage=off
done
yabai \
    -m rule --add label="Finder" app="^Finder$" \
    title="(Copy|Connect|Move|Info|Pref)" \
    manage=off
yabai \
    -m rule --add label="Safari" app="^Safari$" \
    title="^(General|Tabs|Passwords|Websites|Extensions|AutoFill|Search|Security|Privacy|Advanced)$" \
    manage=off
yabai -m rule --add label="Arc" app="^Arc$" manage=on
yabai \
    -m rule --add label="Arc Floats" app="^Arc$" \
    title="^($USER|General|Profiles|Max|Links|Shortcuts|Icon|Advanced|Developer Tools)?$" \
    manage=off
yabai -m rule --add label="Orion" app="^Orion$" manage=on
yabai \
    -m rule --add label="Orion Settings 1" app="^Orion$" \
    title="^(History|Bookmarks|Reading List|Passwords|Extensions|Profiles)?$" \
    manage=off
yabai \
    -m rule --add label="Orion Settings 2" app="^Orion$" \
    title="^(General|Appearance|Tabs|Browsing|Sync|Passwords|Privacy|Search|Websites|Advanced|Plus)?$" manage=off
yabai \
    -m rule --add label="Orion Update" app="^Orion$" \
    title="^Updating Orion$" manage=off
yabai \
    -m rule --add label="Orion Preview" app="^Orion$" \
    title="^Orion Preview" manage=off
yabai \
    -m rule --add label="WeChat Floats" app="^微信$" \
    title!="^(微信|WeChat)$" manage=off
yabai \
    -m rule --add label="TencentMeeting Floats" app="^腾讯会议$" \
    title="^腾讯会议$" manage=off

yabai -m rule --apply
