[manager]
prepend_keymap = [
    { on = "<C-c>", run = "escape", desc = "Exit visual mode, clear selected, or cancel search" },
    { on = [ "q" ], run = "close", desc = "Close window" },
    { on = [ "g", "i" ], run = "cd '~/Library/Mobile Documents/com~apple~CloudDocs'", desc = "Open iCloud documents" },
    { on = "<C-/>", run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },
    { on = [ "c", "m" ], run = "plugin chmod", desc = "Chmod on selected files" },
    { on = "f", run = "plugin jump-to-char", desc = "Jump to char" },
    { on = [ "P" ], run = "plugin toggle-pane max-preview", desc = "Maximize or restore the preview pane" },
    { on = "<C-t>", run = "plugin toggle-pane min-preview", desc = "Show or hide the preview pane" },
    { on = "F", run = "plugin smart-filter", desc = "Smart filter" },
    { on = "<C-d>", run = "plugin diff", desc = "Diff the selected with the hovered file" },
    # { on = [ "l" ], run = "plugin bypass", desc = "Smart enter" },
    # { on = [ "h" ], run = "plugin bypass --args=reverse", desc = "Smart exit" },
    { on = [ "E" ], run = "shell --confirm \" kitty @ launch --type=tab ~/.local/bin/xh -c \\\" ${EDITOR} \\\\\\\"\\$@\\\\\\\"\\\" -- \\\"$@\\\" \"", desc = "Edit in kitty new tab" },
    { on = [ "e" ], run = "open", desc = "Edit" },
    # { on = [ "g", "l" ], run = "plugin --sync follow-link", desc = "Follow the symlink" },  # FIXME: does not work
]
