[manager]
ratio = [2, 4, 3]
linemode = "mtime"

[[opener.edit]]
run = 'kitty @ launch --type=tab --title="$EDITOR \"$@\"" ~/.local/bin/xh -c "$EDITOR \"$@\""'
block = false
for = "macos"

[[opener.edit]]
run = '$EDITOR "$@"'
block = true
for = "linux"

[[plugin.prepend_previewers]]
mime = "application/{,g}zip"
run = "lsar"

[[plugin.prepend_previewers]]
mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}"
run = "lsar"

[[plugin.prepend_previewers]]
mime = "{image,audio,video}/*"
run = "mediainfo"

[[plugin.prepend_previewers]]
mime = "application/x-subrip"
run = "mediainfo"
