[manager]
ratio = [2, 4, 3]
linemode = "mtime"
title_format = "󰇥 │{cwd}"

# [[opener.edit]]
# run = 'kitty @ launch --type=tab ~/.local/bin/xh -c "$EDITOR \"$@\""'
# block = false
# for = "macos"
# desc = "Edit in new tab"

[[opener.edit]]
run = '$EDITOR "$@"'
block = true
# for = "linux"

[[plugin.prepend_previewers]]
mime = "application/{,g}zip"
run = "lsar"

[[plugin.prepend_previewers]]
mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}"
run = "lsar"

[[plugin.prepend_previewers]]
mime = "{image,audio,video}/*"
run = "mediainfo"

[[plugin.prepend_previewers]]
mime = "application/x-subrip"
run = "mediainfo"

[[plugin.append_previewers]]
name = "*"
run = "preview"
