"$schema" = 'https://starship.rs/config-schema.json'

[line_break]
disabled = true

[character]

[package]

[username]

[hostname]
ssh_symbol = ''

[container]
disabled = true

[directory]
fish_style_pwd_dir_length = 1
truncation_length = 1
truncation_symbol = '…/'
