"$schema" = 'https://starship.rs/config-schema.json'

[line_break]
disabled = true

[username]

[hostname]
ssh_symbol = ''

[container]
disabled = true

[directory]
fish_style_pwd_dir_length = 1
truncation_length = 1

[git_branch]
ignore_branches = ['master', 'main']

[python]
disabled = true
