$HOMEBREW_MIRROR = "https://mirrors.ustc.edu.cn"
$HOMEBREW_API_DOMAIN = f"https://mirrors.ustc.edu.cn/homebrew-bottles/api"
$HOMEBREW_BOTTLE_DOMAIN = f"https://mirrors.ustc.edu.cn/homebrew-bottles"
$HOMEBREW_BREW_GIT_REMOTE = f"https://mirrors.ustc.edu.cn/brew.git"
$HOMEBREW_CORE_GIT_REMOTE = f"https://mirrors.ustc.edu.cn/homebrew-core.git"
$HOMEBREW_PIP_INDEX_URL = "https://pypi.tuna.tsinghua.edu.cn/simple"
# $HOMEBREW_INSTALL_BADGE = " "
