# general
shell = "/Users/ko/.local/bin/xh"
live_config_reload = true
import = [
    "~/.config/alacritty/_active_theme.toml",
]

[font]
normal.family = "IosevkaTerm Nerd Font Mono"
normal.style = "Regular"
italic.style = "Light Italic"
size = 21
builtin_box_drawing = false

[window]
dynamic_padding = true
padding = { x = 8, y = 5 }
decorations = "Full"
resize_increments = true

[[hints.enabled]]
command = "open"
hyperlinks = true
mouse.enabled = true
mouse.mods = "Command"
post_processing = true
persist = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"
